name: test
channels:
  - defaults
  - conda-forge

dependencies:
  - matplotlib >= 3.7.2
  - mpi4py >= 3.1.4
  - numba >= 0.57.1
  - numpy >= 1.24.4
  - scipy >= 1.11.1
  - sympy >= 1.12
  - tikzplotlib >= 0.10.1
