# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Regression Test

on:
  push:
    branches: [ devel ]
  workflow_dispatch:

jobs:
  build:
    name: Regression Test (${{ matrix.python-version }})
    runs-on: self-hosted
    timeout-minutes: 1440
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - name: Checkout latest repo version
      uses: actions/checkout@v2
    - name: Cache Miniconda
      uses: actions/cache@v2
      env:
        CACHE_NUMER: 0
      with:
        path: /temp_local/scratch/grp01587/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('environment.yml') }}
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        auto-activate-base: false
        auto-update-conda: true
        environment-file: environment.yml
        miniconda-version: latest
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
        channel-priority: strict
    - name: Conda info
      run: conda info
    - name: CUED Regression Tests
      run: |
        export PYTHONPATH=$PWD
        python tests/test_script.py --path tests --mpin 8
