# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: regression test

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Regression test (${{ matrix.python-version }})
    runs-on: self-hosted
    timeout-minutes: 1440
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        miniconda-version: latest
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: defaults,conda-forge
        channel-priority: strict
    - name: Conda info
      run: conda info
